#!/usr/bin/env bash
#
# Train + SAVE Qwen3-1.7B-Base SFT checkpoints across a few learning rates so
# they appear in the chat_app dropdown for side-by-side comparison.
#
# The earlier LR sweep used output_dir=null (judged by loss curves + sample
# panels), so nothing was saved. This re-runs it with saving on.
#
# PREREQS:
#   * Needs the full GPU (~27 GB). STOP the chat UI first — it holds models in
#     VRAM and would OOM training. (Ctrl-C the `chat_app` process / its terminal.)
#   * ~50 min per LR at 1 epoch on an RTX 5090 (set EPOCHS=3 for full runs).
#
# USAGE (from code/):
#   bash scripts/train_qwen3_lr_sweep.sh                 # all 4 LRs, 1 epoch
#   EPOCHS=3 bash scripts/train_qwen3_lr_sweep.sh        # full 3-epoch runs
#   LRS="2e-5 2e-4" bash scripts/train_qwen3_lr_sweep.sh # just a subset
#
# Then relaunch the UI — the new checkpoints are auto-discovered:
#   uv run --extra ui python -m instruction_tuning.chat_app

cd "$(dirname "$0")/.." || exit 1 # -> code/

RUNS="${RLHF_RUNS:-$HOME/rlhf-runs}"
CFG_DIR="$RUNS/sweep-configs"
EPOCHS="${EPOCHS:-1}"
LRS="${LRS:-5e-6 1e-5 2e-5 2e-4}"
mkdir -p "$CFG_DIR" "$RUNS/wandb"
export WANDB_PROJECT="${WANDB_PROJECT:-rlhf-book}"
export WANDB_DIR="$RUNS/wandb"

# Map a short label like "5e-6" to a YAML-safe float literal "5.0e-6"
to_float() { printf '%s' "$1" | sed -E 's/^([0-9]+)e/\1.0e/'; }

for label in $LRS; do
  lr="$(to_float "$label")"
  out="$RUNS/sft-qwen3-lr${label}-${EPOCHS}ep"
  cfg="$CFG_DIR/lr_${label}_${EPOCHS}ep.yaml"
  cat >"$cfg" <<YAML
# Generated by scripts/train_qwen3_lr_sweep.sh
model_name: Qwen/Qwen3-1.7B-Base
chat_template_source: null
dataset_name: HuggingFaceH4/no_robots
dataset_split: train
max_samples: null
max_length: 2048
lr: ${lr}
num_epochs: ${EPOCHS}
batch_size: 4
gradient_accumulation_steps: 8
warmup_ratio: 0.1
weight_decay: 0.0
max_grad_norm: 1.0
seed: 42
bf16: true
gradient_checkpointing: true
model_device_id: 0
sample_every: 50
sample_max_tokens: 128
sample_max_input_tokens: 512
sample_temperature: 0.7
sample_top_p: 0.9
sample_do_sample: true
wandb_project: null
wandb_run_name: sft-qwen3-lr${label}-${EPOCHS}ep
output_dir: ${out}
YAML

  echo "########## training lr=${label} (${EPOCHS} epoch) -> ${out} ##########"
  uv run python -m instruction_tuning.train_qwen_base --config "$cfg"
  echo "########## done lr=${label} rc=$? ##########"
done

echo
echo "All requested LRs trained. Relaunch the UI to compare them:"
echo "  uv run --extra ui python -m instruction_tuning.chat_app"
